# fly.toml app configuration file generated for sen-d-sparkling-dust-3001 on 2025-08-05T21:48:11+05:00
#
# See https://fly.io/docs/reference/configuration/ for information about how to use this file.
#

app = 'sen-d-sparkling-dust-3001'
primary_region = 'sin'

[build]

[http_service]
  internal_port = 8000
  force_https = true
  auto_stop_machines = 'suspend'
  auto_start_machines = true
  min_machines_running = 0
  processes = ['app']

[[vm]]
  memory = '4gb'
  cpu_kind = 'shared'
  cpus = 4
